name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prisma generate (optional)
        if: ${{ vars.DATABASE_URL || secrets.DATABASE_URL }}
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL || secrets.DATABASE_URL }}
        run: npm run db:gen

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build
